export enum CancelReason {
  DRIVER_NOT_REACHABLE = 'DRIVER_NOT_REACHABLE',
  DRIVER_LATE = 'DRIVER_LATE',
  PRICE_TOO_HIGH = 'PRICE_TOO_HIGH',
  DEPARTURE_ADDRESS_INCORRECT = 'DEPARTURE_ADDRESS_INCORRECT',
  OTHER = 'OTHER',
}
